AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the flow logs Athena table
Resources:
  ConfigAggregatorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRoleForOrganizations
  Aggregator: 
    Type: AWS::Config::ConfigurationAggregator
    Properties: 
      OrganizationAggregationSource: 
        AllAwsRegions: True
        RoleArn: !GetAtt ConfigAggregatorRole.Arn
  AwsConfigAggregatorParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: This contains the AWS Config organizational aggregator
      Type: String
      Name: Jupyter-Config-Aggregator
      Value: !Ref Aggregator
      
Outputs:
    ConfigAggregatorId:
      Value: !Ref Aggregator