AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an organizational cloudtrail bucket
Parameters:
  OrgId:
    Type: String
    Description: The ID of the AWS Organization
Resources:
  CfnBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CfnBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref CfnBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AWSCloudFormation
          Effect: Allow
          Principal:
            "Service": 
              - "cloudformation.amazonaws.com"
          Action:
          - 's3:ListBucket'
          Resource: 
          - !Sub 'arn:aws:s3:::${CfnBucket}'
        - Sid: AWSCloudFormation2
          Effect: Allow
          Principal:
            "Service": 
              - "cloudformation.amazonaws.com"
          Action:
          - 's3:GetObject'
          Resource: 
          - !Sub 'arn:aws:s3:::${CfnBucket}/*'
        - Sid: GetObjectOrganization
          Effect: Allow
          Principal:
            AWS:
            - '*'
          Action:
          - 's3:ListBucket'
          Resource: 
          - !Sub 'arn:aws:s3:::${CfnBucket}'
          Condition:
            StringEquals:
              "aws:PrincipalOrgID": !Ref OrgId
        - Sid: GetObjectOrganization2
          Effect: Allow
          Principal:
            AWS:
            - '*'
          Action:
          - 's3:GetObject'
          Resource: 
          - !Sub 'arn:aws:s3:::${CfnBucket}/*'
          Condition:
            StringEquals:
              "aws:PrincipalOrgID": !Ref OrgId
              
Outputs:
  CfnBucket:
      Value: !Ref CfnBucket
      