Description: "Create basic notebook instance"
Description: >-
  Creates a SageMaker Jupyter runbook configured to run incident response notebools. All the parameters are optional, 
  and to get started, deploy this notebook leaving all the parameters blank.
Parameters:
  SsoUrl:
    Type: String
    Default: ''
    Description: The URL for the IAM Identity Center (SSO)
  SsoRegion:
    Type: String
    Default: ''
    Description: The Region for the IAM Identity Center (SSO)
  LinkedRoles:
    Type: String
    Default: ''
    Description: A comma separated list of roles urns in that this notebook will have access via role assumption.
  DefaultRole:
    Type: String
    Default: ''
    Description: (Optional) The default role ARN that this account will have access.
Conditions:
  AssumeRolePermission: !Not [!Equals [!Ref LinkedRoles, '']]
Resources:
  ExecutionRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        - arn:aws:iam::aws:policy/AmazonAthenaFullAccess
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
        - 
          Effect: "Allow"
          Principal: 
            Service: 
              - "sagemaker.amazonaws.com"
          Action: 
          - "sts:AssumeRole"
      Path: "/"
      Policies:
        - !If 
          - AssumeRolePermission
          - PolicyName: assume-roles
            PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
                - Effect: "Allow"
                  Action: 
                    - "sts:AssumeRole"
                  Resource: !Split 
                              - ','
                              - !Ref LinkedRoles
          - !Ref AWS::NoValue
        - PolicyName: write-logs
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:DescribeLogStreams"
                  - "logs:PutLogEvents"
                  - "logs:GetLogEvents"
                Resource: 
                - '*'

